Mobile menu
firstpj/Portfolio-Mobile-first-set-up pull request #9
Opened 2023-04-17 11:58 UTC by firstpj

2023-04-17 14:11 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @firstpj 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- You just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-17 14:11 UTC, AbelG101 commented on index.html
https://github.com/firstpj/Portfolio-Mobile-first-set-up/blob/6a512ba271114628386b3ad3566f6ac1fdacd340/index.html#L27-L33
- [ ] Great job adding the sidebar but as specified In the project requirements when the user clicks (or taps) any of the mobile menu options, the mobile menu should disappear. You seem to be missing this functionality so I advise you to fix it.
- [ ] Another thing I've noticed is that the "Portfolio" link in the menu bar isn't working it should normally take the user to the home section of your page, so please make sure to fix it as well. ✔
- Here's the project requirements as a reminder:
  ![image](https://user-images.githubusercontent.com/104968236/232508971-b0951457-7df1-41a6-8ae8-b683feaa8cfb.png)

2023-04-17 14:11 UTC, AbelG101 commented on .eslintrc.json
**THIS COMMENT IS REGARDING THE README OF YOUR PROJECT AND NOT THIS FILE**
- [ ] Please make sure to update the "Authors" section of the readme whenever you have new collaborators as this will make the readme in sync with the GitHub collaborators feature and avoid any confusions
- Here's how it looks now:
  ![image](https://user-images.githubusercontent.com/104968236/232510324-95fb51e3-2de1-4ccc-8057-1228ca7a83e9.png)

2023-04-18 12:10 UTC, aamirkhan2478 requested changes
Hi @firstpj & @maryam0007, 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linter passed
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-18 12:10 UTC, aamirkhan2478 commented on README.md
> +
- [ ] As mentioned by the previous reviewer :point_up_2: add your partner details but you just add your partner name kindly add your partner details also :slightly_smiling_face: check below :point_down:  the example :+1: 

**Example**
![Screenshot from 2023-04-18 17-02-06](https://user-images.githubusercontent.com/45226848/232771185-0a8be3db-7665-4938-a781-60206ad69bc1.png)

2023-04-19 15:29 UTC, divinecharlotte commented on index.html
> -            <li><a href="#contact">Contacts</a></li>
- [ ] I can see that you added some of the required changes by the previous reviewer good job so far 👍 but there is something you are still missing as requested by the previous reviewer kindly consider making sure that when someone clicks any of the links the whole menu dissapear menu but in your case it's still not disappearing kindly fix it check the image below to easily understand it 👇 
- 
<img width="385" alt="Screen Shot 2023-04-19 at 17 22 36" src="https://user-images.githubusercontent.com/60146030/233124703-f5ac2b82-9a1e-4c05-ae10-b5ba37cb5e69.png">

- [ ]  last but not least kindly consider making sure that your mobile menu looks like the one given in the design make sure that the blue background covers the whole page even the header to have an exact duplicate of the provided design check the images on this [link ](https://github.com/firstpj/Portfolio-Mobile-first-set-up/pull/9#discussion_r1169922670) for more clarification

2023-04-22 00:04 UTC, didierganthier requested changes
Hi @firstpj and @maryam0007 ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/3oEduMcvxTNPlGuhH2/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- N/A

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-04-22 00:04 UTC, didierganthier commented on index.html
> +			  <li class="links">About</li>
Also as requested by the previous reviewer make sure to adjust the background color of the menu 🎨 you did a great job with the blur but the color isn't quite right yet, take a look

## What you have

![Screenshot 2023-04-21 at 20 01 50](https://user-images.githubusercontent.com/45739963/233750649-512c4d89-f0c9-463d-b5b7-093da4132e9a.png)

## What you need

![Screenshot 2023-04-21 at 20 02 15](https://user-images.githubusercontent.com/45739963/233750683-fede3150-c1f1-4691-b0c9-47766961ac6a.png)

2023-04-22 10:17 UTC, Rustamxon7 approved these changes
Hi @firstpj, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Developer-512px-10](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯
3. Well-implemented code 💯 

## Optional suggestions
No optional suggestions :)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-23 21:39 UTC, closed without merging